title = "Peg's Adventures"
baseURL = "pegeaton.github.io"
languageCode = "en-us"
theme = "ananke"
themesDir = "./themes"
resourceDir = "./resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Peg's blog"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/logo.png"
  description = "Eclectic Adventures in the virtual and physical world."
  twitter = "https://twitter.com/pegeaton"
  instagram = ""
  youtube = ""
  github = "https://github.com/pegeaton"
  # gitlab = "https://gitlab.com/pegeaton"
  linkedin = "https://linkedin.com/in/pegeaton"
  # facebook = "https://facebook.com/peg.eaton.9"
  slack = ""
  mastodon = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/LittleDiamond.jpg"
  recent_posts_number = 3 
